# Definir la URL base y las 49 categorías
base_url = "https://www.carrefour.com.ar/"

categorias_deseadas = [
                        "almacen/sal-aderezos-y-saborizadores/sal",
                        "almacen/aceites-y-vinagres/vinagres-acetos-y-limon",
                        "almacen/enlatados-y-conservas/conservas-y-salsas-de-tomate",
                        "almacen/enlatados-y-conservas/conservas-de-legumbres-y-vegetales",
                        "Almacen/Arroz-y-legumbres/Arroz",
                        "Almacen/Arroz-y-legumbres/Legumbres",
                        "Almacen/Pastas-secas/Fideos-largos",
                        "Almacen/Harinas/Harinas-comunes-y-leudantes",
                        "almacen/harinas/polentas",
                        "almacen/aceites-y-vinagres/aceites-comunes",
                        "lacteos-y-productos-frescos/dulce-de-membrillo-y-otros-dulces",
                        "desayuno-y-merienda/mermeladas-y-otros-dulces/dulce-de-leche",
                        "lacteos-y-productos-frescos/huevos",
                        "Lacteos-y-productos-frescos/Leches",
                        "Lacteos-y-productos-frescos/Quesos",
                        "panaderia/panificados/panes-lacteados-y-de-mesa",
                        "Bebidas/Jugos/Jugos-en-polvo",
                        "soda",
                        "desayuno-y-merienda/cafe/cafe-instantaneo",
                        "desayuno-y-merienda/azucar-y-endulzantes/azucar",
                        "Desayuno-y-merienda/Infusiones/Te",
                        "Desayuno-y-merienda/Yerba",
                        "desayuno-y-merienda/galletitas-bizcochitos-y-tostadas",
                        "Desayuno-y-merienda/Mermeladas-y-otros-dulces/Mermeladas-dulces-y-jaleas",
                        "Limpieza/Lavandinas",
                        "Limpieza/Limpieza-de-cocina/Detergentes",
                        "Limpieza/Articulos-de-limpieza/Esponjas",
                        "Limpieza/Desodorantes-de-ambiente/Desodorantes-y-desinfectantes",
                        "Limpieza/Limpieza-de-pisos-y-muebles/Limpiadores-de-piso",
                        "Limpieza/Limpieza-de-la-ropa/Jabones-para-la-ropa",
                        "Limpieza/Limpieza-de-la-ropa/Suavizantes-para-la-ropa",
                        "Limpieza/Articulos-de-limpieza/Trapos-y-panos",
                        "limpieza/limpieza-de-cocina/limpiadores-cremosos",
                        "Limpieza/Papeles-higienicos",
                        "perfumeria-y-farmacia/Proteccion-femenina/Toallitas-femeninas",
                        "perfumeria-y-farmacia/Jabones/Jabones-en-barra",
                        "perfumeria-y-farmacia/Cuidado-dental/Pasta-dental",
                        "perfumeria-y-farmacia/Cuidado-del-cabello/Shampoos",
                        "perfumeria-y-farmacia/Cuidado-corporal/Afeitado",
                        "perfumeria-y-farmacia/Cuidado-del-cabello/Acondicionadores",
                        "perfumeria-y-farmacia/Antitranspirantes-y-desodorantes/En-aerosol",
                        "perfumeria-y-farmacia/Cuidado-dental/Cepillos-de-dientes",
                        "Carnes-y-pescados/Carne-vacuna",
                        "Carnes-y-pescados/Pollo-y-granja",
                        "Frutas-y-verduras/Verduras",
                        "Frutas-y-verduras/Frutas",
                        "jugueteria-y-libreria/libreria/resmas-y-accesorios-de-oficina",
                        "jugueteria-y-libreria/libreria/lapices-lapiceras-y-marcadores",
                        "jugueteria-y-libreria/libreria/accesorios-de-libreria"
                        ]

# Obtener los links de las categorías
links_categorias = [f"{base_url}{cat}" for cat in categorias_deseadas]